using CheatOnYourDayOnes.CameraSystem;
using CheatOnYourDayOnes.World;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

namespace CheatOnYourDayOnes.Vehicles
{
    [RequireComponent(typeof(Rigidbody))]
    public sealed class DriveableCar : MonoBehaviour
    {
        [SerializeField] private Transform driverSeat, exitPoint, centerOfMass;
        [Header("Arcade Vehicle Physics")]
        [SerializeField] private float topSpeed = 13.5f;
        [SerializeField] private float reverseTopSpeed = 4.5f;
        [SerializeField] private float forwardAcceleration = 2.15f;
        [SerializeField] private float reverseAcceleration = 1.8f;
        [SerializeField] private float engineBraking = 1.15f;
        [SerializeField] private float brakeAcceleration = 10f;
        [SerializeField] private float steeringRate = 68f;
        [SerializeField] private float highSpeedSteerFactor = .42f;
        [SerializeField] private float lateralGripLowSpeed = 10f, lateralGripHighSpeed = 4.5f;
        [SerializeField] private float throttleResponse = 2.1f, steeringResponse = 9f;
        [SerializeField] private float interactionDistance = 3.5f, tyreGroundClearance = .015f;
        [SerializeField] private float npcHitPadding = .55f;
        [Header("NPC impact response")]
        [SerializeField] private float fullStopBelowKmh = 20f;
        [SerializeField] private float heavyBrakeBelowKmh = 30f;
        [SerializeField, Range(0f,1f)] private float mediumImpactSpeedRetention = .45f;

        private Rigidbody _rb; private Transform _driver; private CharacterController _driverController; private Behaviour _networkController; private VehicleInteractor _interactor;
        private Renderer[] _driverRenderers; private bool[] _driverRendererStates; private Collider[] _driverColliders; private bool[] _driverColliderStates;
        private ThirdPersonCamera _camera; private BoxCollider _chassisCollider;
        private readonly List<Renderer> _wheelRenderers=new(); private readonly List<SphereCollider> _wheelSupportColliders=new();
        private readonly HashSet<NPCWanderer> _npcHitThisContact=new();
        private bool _occupied,_ignoreExitUntilEReleased; private float _rawThrottle,_rawSteer,_throttle,_steer; private bool _brake; private float _driveSpeed,_debugTimer,_modelScale=1f;
        public bool IsOccupied=>_occupied; public Vector3 DriveVelocity=>transform.forward*_driveSpeed;

        private void Awake(){_rb=GetComponent<Rigidbody>();DetectWheelsAndScale();ConfigureRigidbody();RebuildVehicleColliders();}
        private void ConfigureRigidbody(){_rb.mass=1350f;_rb.useGravity=true;_rb.isKinematic=false;_rb.constraints=RigidbodyConstraints.None;_rb.linearDamping=.02f;_rb.angularDamping=3.2f;_rb.interpolation=RigidbodyInterpolation.Interpolate;_rb.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;_rb.maxAngularVelocity=4f;_rb.centerOfMass=centerOfMass!=null?transform.InverseTransformPoint(centerOfMass.position):new Vector3(0,-.35f*_modelScale,.05f*_modelScale);}
        private void DetectWheelsAndScale(){_wheelRenderers.Clear();Renderer[] rs=GetComponentsInChildren<Renderer>(true);if(rs.Length==0)return;Bounds all=rs[0].bounds;foreach(Renderer r in rs){if(r==null)continue;all.Encapsulate(r.bounds);string n=r.name.ToLowerInvariant(),p=r.transform.parent!=null?r.transform.parent.name.ToLowerInvariant():"";if(LooksLikeWheelName(n)||LooksLikeWheelName(p))_wheelRenderers.Add(r);}float length=Mathf.Max(all.size.x,all.size.z);_modelScale=Mathf.Clamp(length/4.5f,.5f,3f);Debug.Log($"[CYDOY] Car setup: visualLength={length:F2}, modelScale={_modelScale:F2}, wheelRenderers={_wheelRenderers.Count}",this);}
        private static bool LooksLikeWheelName(string n)=>n.Contains("wheel")||n.Contains("tire")||n.Contains("tyre")||n.Contains("reifen")||n.Contains("felge")||n.Contains("rim")||n.Contains("roue")||n.Contains("rad_");
        private void Update(){if(!_occupied||Keyboard.current==null)return;_rawThrottle=(Keyboard.current.wKey.isPressed?1f:0f)-(Keyboard.current.sKey.isPressed?1f:0f);_rawSteer=(Keyboard.current.dKey.isPressed?1f:0f)-(Keyboard.current.aKey.isPressed?1f:0f);_brake=Keyboard.current.spaceKey.isPressed;_throttle=Mathf.MoveTowards(_throttle,_rawThrottle,throttleResponse*Time.deltaTime);_steer=Mathf.MoveTowards(_steer,_rawSteer,steeringResponse*Time.deltaTime);if(_ignoreExitUntilEReleased){if(!Keyboard.current.eKey.isPressed)_ignoreExitUntilEReleased=false;}else if(Keyboard.current.eKey.wasPressedThisFrame)Exit();}
        private void FixedUpdate(){if(!_occupied)return;if(_brake)_driveSpeed=Mathf.MoveTowards(_driveSpeed,0,brakeAcceleration*Time.fixedDeltaTime);else if(_throttle>.01f)_driveSpeed=Mathf.MoveTowards(_driveSpeed,topSpeed,forwardAcceleration*_throttle*Time.fixedDeltaTime);else if(_throttle<-.01f)_driveSpeed=Mathf.MoveTowards(_driveSpeed,-reverseTopSpeed,reverseAcceleration*-_throttle*Time.fixedDeltaTime);else _driveSpeed=Mathf.MoveTowards(_driveSpeed,0,engineBraking*Time.fixedDeltaTime);
            Vector3 local=transform.InverseTransformDirection(_rb.linearVelocity);float speed01=Mathf.Clamp01(Mathf.Abs(_driveSpeed)/topSpeed),grip=Mathf.Lerp(lateralGripLowSpeed,lateralGripHighSpeed,speed01),lateral=Mathf.MoveTowards(local.x,0,grip*Time.fixedDeltaTime);Vector3 wanted=transform.TransformDirection(new Vector3(lateral,0,_driveSpeed));wanted.y=_rb.linearVelocity.y;_rb.linearVelocity=wanted;
            float authority=Mathf.Clamp01(Mathf.Abs(_driveSpeed)/1.7f),mult=Mathf.Lerp(1f,highSpeedSteerFactor,speed01),rev=_driveSpeed<-.05f?-1f:1f,yaw=_steer*steeringRate*mult*authority*rev*Time.fixedDeltaTime;if(Mathf.Abs(yaw)>.0001f)_rb.MoveRotation(_rb.rotation*Quaternion.Euler(0,yaw,0));Vector3 av=_rb.angularVelocity;av.x*=.72f;av.z*=.72f;_rb.angularVelocity=av;DetectNPCHits();_debugTimer+=Time.fixedDeltaTime;if(_debugTimer>=1&&Mathf.Abs(_rawThrottle)>.1f){_debugTimer=0;Debug.Log($"[CYDOY] CAR DRIVE commanded={_driveSpeed:F2}m/s actual={transform.InverseTransformDirection(_rb.linearVelocity).z:F2}m/s",this);}}
        private void DetectNPCHits(){Bounds b=_chassisCollider!=null?_chassisCollider.bounds:new Bounds(transform.position,new Vector3(2,1.5f,4));Vector3 half=b.extents+Vector3.one*npcHitPadding;Collider[] hits=Physics.OverlapBox(b.center,half,transform.rotation,~0,QueryTriggerInteraction.Collide);HashSet<NPCWanderer> current=new();foreach(Collider hit in hits){if(hit==null||hit.transform.IsChildOf(transform))continue;NPCWanderer npc=hit.GetComponentInParent<NPCWanderer>();if(npc==null)continue;current.Add(npc);if(_npcHitThisContact.Contains(npc))continue;float kmh=Mathf.Abs(_driveSpeed)*3.6f;if(npc.HitByVehicle(DriveVelocity,transform.position)){ApplyNPCImpactSpeedResponse(kmh);_npcHitThisContact.Add(npc);Debug.Log($"[CYDOY] NPC IMPACT tier at {kmh:F1} km/h -> car {_driveSpeed:F2} m/s",this);}}_npcHitThisContact.RemoveWhere(n=>!current.Contains(n));}
        private void ApplyNPCImpactSpeedResponse(float kmh){float sign=Mathf.Sign(_driveSpeed==0?1:_driveSpeed);if(kmh<=fullStopBelowKmh){_driveSpeed=0;Vector3 v=_rb.linearVelocity;Vector3 planar=Vector3.ProjectOnPlane(v,Vector3.up);_rb.linearVelocity=v-planar;}else if(kmh<heavyBrakeBelowKmh){_driveSpeed*=mediumImpactSpeedRetention;Vector3 local=transform.InverseTransformDirection(_rb.linearVelocity);local.z=_driveSpeed;_rb.linearVelocity=transform.TransformDirection(local);}else{_driveSpeed=Mathf.Abs(_driveSpeed)*sign;}}
        public float DistanceFrom(Vector3 p){float best=float.MaxValue;foreach(Collider c in GetComponentsInChildren<Collider>(true)){if(c==null||!c.enabled||c.isTrigger)continue;best=Mathf.Min(best,Vector3.Distance(p,c.ClosestPoint(p)));}return best<float.MaxValue?best:Vector3.Distance(p,transform.position);}
        public bool TryEnter(Transform player){if(_occupied||player==null||DistanceFrom(player.position)>interactionDistance)return false;_driver=player;_driverController=player.GetComponent<CharacterController>();_networkController=player.GetComponent<CheatOnYourDayOnes.Player.NetworkPlayerController>();_interactor=player.GetComponent<VehicleInteractor>();if(_networkController!=null)_networkController.enabled=false;if(_interactor!=null)_interactor.enabled=false;_driverRenderers=player.GetComponentsInChildren<Renderer>(true);_driverRendererStates=new bool[_driverRenderers.Length];for(int i=0;i<_driverRenderers.Length;i++){_driverRendererStates[i]=_driverRenderers[i].enabled;_driverRenderers[i].enabled=false;}_driverColliders=player.GetComponentsInChildren<Collider>(true);_driverColliderStates=new bool[_driverColliders.Length];for(int i=0;i<_driverColliders.Length;i++){_driverColliderStates[i]=_driverColliders[i].enabled;_driverColliders[i].enabled=false;}if(_driverController!=null)_driverController.enabled=false;Transform seat=driverSeat!=null?driverSeat:transform;player.SetParent(seat,false);player.localPosition=Vector3.zero;player.localRotation=Quaternion.identity;_camera=Object.FindFirstObjectByType<ThirdPersonCamera>(FindObjectsInactive.Include);if(_camera!=null)_camera.EnterVehicleMode(transform);DetectWheelsAndScale();ConfigureRigidbody();RebuildVehicleColliders();PutTyresOnGround();_driveSpeed=_throttle=_steer=0;_rb.linearVelocity=Vector3.zero;_rb.angularVelocity=Vector3.zero;_rb.WakeUp();_occupied=true;_ignoreExitUntilEReleased=true;_npcHitThisContact.Clear();Debug.Log($"[CYDOY] Vehicle active. topSpeed={topSpeed:F1}m/s acceleration={forwardAcceleration:F2}m/s²",this);return true;}
        public void Exit(){if(!_occupied||_driver==null)return;Transform p=_driver;p.SetParent(null,true);p.position=exitPoint!=null?exitPoint.position:transform.position-transform.right*1.8f+Vector3.up*.25f;p.rotation=Quaternion.Euler(0,transform.eulerAngles.y,0);if(_camera!=null)_camera.ExitVehicleMode(p);if(_driverRenderers!=null)for(int i=0;i<_driverRenderers.Length;i++)if(_driverRenderers[i]!=null)_driverRenderers[i].enabled=_driverRendererStates[i];if(_driverColliders!=null)for(int i=0;i<_driverColliders.Length;i++)if(_driverColliders[i]!=null)_driverColliders[i].enabled=_driverColliderStates[i];if(_driverController!=null)_driverController.enabled=true;if(_networkController!=null)_networkController.enabled=true;if(_interactor!=null)_interactor.enabled=true;_driver=null;_occupied=false;_rawThrottle=_rawSteer=_throttle=_steer=_driveSpeed=0;_brake=false;_npcHitThisContact.Clear();}
        private void RebuildVehicleColliders(){foreach(Collider c in GetComponentsInChildren<Collider>(true)){if(c==null||c==_chassisCollider||_wheelSupportColliders.Contains(c as SphereCollider)||c.isTrigger)continue;c.enabled=false;}foreach(SphereCollider old in _wheelSupportColliders)if(old!=null)Destroy(old.gameObject);_wheelSupportColliders.Clear();Renderer[] rs=GetComponentsInChildren<Renderer>(true);if(rs.Length==0)return;Bounds all=rs[0].bounds;foreach(Renderer r in rs)if(r!=null)all.Encapsulate(r.bounds);Vector3 min=new(float.PositiveInfinity,float.PositiveInfinity,float.PositiveInfinity),max=new(float.NegativeInfinity,float.NegativeInfinity,float.NegativeInfinity);foreach(Vector3 corner in BoundsCorners(all)){Vector3 l=transform.InverseTransformPoint(corner);min=Vector3.Min(min,l);max=Vector3.Max(max,l);}if(_chassisCollider==null){_chassisCollider=GetComponent<BoxCollider>();if(_chassisCollider==null)_chassisCollider=gameObject.AddComponent<BoxCollider>();}Vector3 raw=max-min;_chassisCollider.size=new Vector3(raw.x*.82f,raw.y*.32f,raw.z*.84f);_chassisCollider.center=new Vector3((min.x+max.x)*.5f,min.y+raw.y*.66f,(min.z+max.z)*.5f);_chassisCollider.enabled=true;_chassisCollider.isTrigger=false;foreach(Renderer wheel in _wheelRenderers){if(wheel==null||!wheel.enabled)continue;Bounds wb=wheel.bounds;float radiusWorld=Mathf.Clamp(wb.size.y*.47f,.16f*_modelScale,.48f*_modelScale);GameObject support=new("CYDOY_WheelSupport_"+wheel.name);support.transform.SetParent(transform,false);support.transform.position=wb.center;SphereCollider sphere=support.AddComponent<SphereCollider>();float ps=Mathf.Max(.0001f,Mathf.Max(Mathf.Abs(transform.lossyScale.x),Mathf.Max(Mathf.Abs(transform.lossyScale.y),Mathf.Abs(transform.lossyScale.z))));sphere.radius=radiusWorld/ps;_wheelSupportColliders.Add(sphere);}Debug.Log($"[CYDOY] Vehicle colliders rebuilt: wheelSupports={_wheelSupportColliders.Count}",this);}
        private void PutTyresOnGround(){if(_wheelRenderers.Count==0)return;float bottom=float.PositiveInfinity;Vector3 avg=Vector3.zero;int count=0;foreach(Renderer wheel in _wheelRenderers){if(wheel==null||!wheel.enabled)continue;bottom=Mathf.Min(bottom,wheel.bounds.min.y);avg+=wheel.bounds.center;count++;}if(count==0)return;avg/=count;RaycastHit[] hits=Physics.RaycastAll(new Vector3(avg.x,avg.y+3f*_modelScale,avg.z),Vector3.down,10f*_modelScale,~0,QueryTriggerInteraction.Ignore);bool found=false;float ground=float.NegativeInfinity;foreach(RaycastHit hit in hits){if(hit.collider==null||hit.transform==transform||hit.transform.IsChildOf(transform)||hit.normal.y<.65f)continue;if(!found||hit.point.y>ground){ground=hit.point.y;found=true;}}if(!found)return;float delta=ground+tyreGroundClearance-bottom;transform.position+=Vector3.up*delta;Physics.SyncTransforms();}
        private static Vector3[] BoundsCorners(Bounds b){Vector3 min=b.min,max=b.max;return new[]{new Vector3(min.x,min.y,min.z),new Vector3(max.x,min.y,min.z),new Vector3(min.x,max.y,min.z),new Vector3(max.x,max.y,min.z),new Vector3(min.x,min.y,max.z),new Vector3(max.x,min.y,max.z),new Vector3(min.x,max.y,max.z),new Vector3(max.x,max.y,max.z)};}
    }
}
